### ISSUE TITLE
Structure for Person Roles

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#631]
Proposed structure for people roles:

1. Remove the `status` field from people;
2. Add additional structure to the roles field, as follows:
```
roles:
  - name: Head of Graduate Programs
    type: staff
    term: current
  - name: Praxis Fellow
    type: fellowship
    term: 2012-2013
  - name: Graduate Fellow
    type: fellowship
    term: 2015-2016
```
