### ISSUE TITLE
Remove post header text from excerpt

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#653]
So "crossposted from" etc. header text doesn't appear in the excerpt, e.g.:

<img width="820" alt="screen shot 2019-01-15 at 1 54 17 pm" src="https://user-images.githubusercontent.com/899033/51202591-128b6b80-18cd-11e9-8209-9bc7815a3a0a.png">

**Comment by jeremyboggs** [comment]
@amandavisconti To reliably do this, we'd need to standardize how we indicate a post has been crossposted elsewhere. Ideally, this would be something we'd add to the post YAML, maybe soemthign like this:

```yaml
crossposted:
  - url: https://example.com/2019/01/01/post-title
    site_title:  Blog Title
```

Then, we could have limitless options for displaying that (and for not displaying it in various contexts). In the meantime, we could 1) take a cursory look over how folks have indicated this; 2) make a list of those strings; 3) filter out those strings explicitly.
