### ISSUE TITLE
_config.yml 'exclude' values still being built into '_site/'

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#74]
- Realized I needed to make sure the `docs/` folder didn't get built into the local site, so I went to edit the `_config.yml` file
- Kept getting built in, so I ended up looking at it more closely - turns out `Gemfile` and `Gemfile.lock` *also* are being built into `_site/`

- *NB: this may only affect Windows machines.*

**Comment by kbdonnally** [comment]
Update: tried using the alternative "array" syntax and still no dice

Syntax:

```yaml
# current
exclude:
 - Gemfile
 - Gemfile.lock

# tried to no avail
exclude: [Gemfile, Gemfile.lock]
```
